### ISSUE TITLE
README: consider putting sections with elaborate directions in collapsible divs for improved readability

### ISSUE THREAD

**Issue by luzpaz** [NikraDAP/FreeCAD-NikraDAP#4]
How to create a [collapsed div](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab) in markdown.

Suggestion:
* rename Installation sub-sections `Automatic installation (recommended)` and `Manual installation` respectively. 
* Put the `Manual installation` section in a collapsed div since it's less relevant now that the Automatic approach is available
* Put the 'Hello World' section in a collapsed div
* Add a **License** section and link to the LICENSE file under it.

**Comment by ljplessis** [comment]
Thanks for the suggestions, @luzpaz!

Thank you to @Dewald141 for making the changes to the README Documentation
